CREATE BITMAP INDEX bji_faits_fraude
ON FAIT_TRANSACTIONS_DETAILLE (DIM_INFO_TRANSACTION.est_fraude)
FROM FAIT_TRANSACTIONS_DETAILLE, DIM_INFO_TRANSACTION
WHERE FAIT_TRANSACTIONS_DETAILLE.info_transaction_id = DIM_INFO_TRANSACTION.INFOTRANSACTION_KEY;

CREATE BITMAP INDEX bji_faits_pays
ON FAIT_TRANSACTIONS_DETAILLE (DIM_LIEUX.pays)
FROM FAIT_TRANSACTIONS_DETAILLE, DIM_LIEUX
WHERE FAIT_TRANSACTIONS_DETAILLE.lieu_id = DIM_LIEUX.LIEU_KEY;

CREATE BITMAP INDEX bji_faits_bloque
ON FAIT_TRANSACTIONS_DETAILLE (DIM_INFO_TRANSACTION.est_bloque)
FROM FAIT_TRANSACTIONS_DETAILLE, DIM_INFO_TRANSACTION
WHERE FAIT_TRANSACTIONS_DETAILLE.info_transaction_id = DIM_INFO_TRANSACTION.INFOTRANSACTION_KEY;

CREATE BITMAP INDEX bji_faits_profession
ON FAIT_TRANSACTIONS_DETAILLE (DIM_CLIENTS.profession)
FROM FAIT_TRANSACTIONS_DETAILLE, DIM_CLIENTS
WHERE FAIT_TRANSACTIONS_DETAILLE.client_id = DIM_CLIENTS.CLIENT_KEY;

CREATE BITMAP INDEX bji_faits_segment
ON FAIT_TRANSACTIONS_DETAILLE (DIM_CLIENTS.segment_comportemental)
FROM FAIT_TRANSACTIONS_DETAILLE, DIM_CLIENTS
WHERE FAIT_TRANSACTIONS_DETAILLE.client_id = DIM_CLIENTS.CLIENT_KEY;
