CREATE MATERIALIZED VIEW MV_CLIENT_DATE_LIEU_AGG
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
ENABLE QUERY REWRITE
AS
SELECT
    c.TYPE_CLIENT,
    c.PROFESSION,
    c.SEGMENT_COMPORTEMENTAL,
    d.ANNEE,
    d.NOM_MOIS,
    d.NUMERO_MOIS,
    l.PAYS,
    i.EST_FRAUDE AS est_frauduleux,
    i.EST_BLOQUE AS est_bloque,
    COUNT(*) AS nb_transactions,
    SUM(f.MONTANT_TOTAL) AS sum_montant_total,
    SUM(CASE WHEN i.EST_FRAUDE = 1 THEN f.MONTANT_TOTAL ELSE 0 END) AS sum_montant_frauduleux,
    COUNT(DISTINCT f.CLIENT_ID) AS nb_clients_uniques, 
    SUM(f.MONTANT_TOTAL) AS agg_sum_montant,
    COUNT(f.MONTANT_TOTAL) AS agg_count_montant
FROM
    FAIT_TRANSACTIONS_DETAILLE f
JOIN
    DIM_CLIENTS c ON f.CLIENT_ID = c.CLIENT_KEY
JOIN
    DIM_DATE d ON f.DATE_ID = d.DATE_KEY
JOIN
    DIM_LIEUX l ON f.LIEU_ID = l.LIEU_KEY
JOIN
    DIM_INFO_TRANSACTION i ON f.INFO_TRANSACTION_ID = i.INFOTRANSACTION_KEY
GROUP BY
    c.TYPE_CLIENT,
    c.PROFESSION,
    c.SEGMENT_COMPORTEMENTAL,
    d.ANNEE,
    d.NOM_MOIS,
    d.NUMERO_MOIS,
    l.PAYS,
    i.EST_FRAUDE,
    i.EST_BLOQUE;

CREATE MATERIALIZED VIEW MV_OPERATION_TEMPS_AGG
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
ENABLE QUERY REWRITE
AS
SELECT
    op.CANAL AS type_canal,
    op.TYPE_DISPOSITIF AS type_dispositif,
    op.LIBELLE_OPERATION AS libelle_operation,
    t.PERIODE_JOURNEE AS periode_journee,
    t.TRANCHE_HORAIRE AS tranche_horaire,
    COUNT(*) AS nb_transactions,
    SUM(f.SCORE_FRAUDE) AS sum_score_fraude,
    COUNT(f.SCORE_FRAUDE) AS count_score_fraude,
    SUM(f.DUREE_TRAITEMENT_MS) AS sum_duree_traitement,
    COUNT(f.DUREE_TRAITEMENT_MS) AS count_duree_traitement
FROM
    FAIT_TRANSACTIONS_DETAILLE f
JOIN
    DIM_MODES_OPERATION op ON f.MODE_OPERATION_ID = op.MODES_OPERATION_KEY
JOIN
    DIM_TEMPS t ON f.HEURE_ID = t.TEMPS_KEY
GROUP BY
    op.CANAL,
    op.TYPE_DISPOSITIF,
    op.LIBELLE_OPERATION,
    t.PERIODE_JOURNEE,
    t.TRANCHE_HORAIRE;

CREATE MATERIALIZED VIEW MV_FINANCE_MARKETING_AGG
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
ENABLE QUERY REWRITE
AS
SELECT
    m.CATEGORIE_MARCHAND AS categorie_marchand,
    dev.NOM_DEVISE AS nom_devise,
    dev.EST_CRYPTO AS est_crypto,
    p.NOM_PLAN AS nom_plan,
    op.LIBELLE_OPERATION AS libelle_operation,
    COUNT(*) AS nb_transactions,
    SUM(f.MONTANT_TOTAL) AS sum_montant_total,
    SUM(f.FRAIS) AS sum_frais,
    SUM(f.CASHBACK_GAGNE) AS sum_cashback_gagne,
    SUM(CASE WHEN op.LIBELLE_OPERATION = 'depot' THEN f.MONTANT_TOTAL ELSE 0 END) AS sum_depots,
    SUM(CASE WHEN op.LIBELLE_OPERATION IN ('retrait', 'paiement', 'virement') THEN f.MONTANT_TOTAL ELSE 0 END) AS sum_sorties
FROM
    FAIT_TRANSACTIONS_DETAILLE f
JOIN
    DIM_MARCHANDS m ON f.MARCHAND_ID = m.MARCHAND_KEY
JOIN
    DIM_DEVISES dev ON f.DEVISE_ID = dev.DEVISE_KEY
JOIN
    DIM_PLANS p ON f.PLAN_ID = p.PLAN_KEY
JOIN
    DIM_MODES_OPERATION op ON f.MODE_OPERATION_ID = op.MODES_OPERATION_KEY
GROUP BY
    m.CATEGORIE_MARCHAND,
    dev.NOM_DEVISE,
    dev.EST_CRYPTO,
    p.NOM_PLAN,
    op.LIBELLE_OPERATION;
